=== dd482IT/columnal-wpi/records/app/src/main/funcdoc/funcdoc.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="functionDocumentation">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="functionGroup" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="description" type="xs:string"/>
                            <xs:element name="function" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="scope" type="xs:string" minOccurs="0"/>
                                        <xs:element name="argType" type="xs:string"/>
                                        <xs:element name="returnType" type="xs:string"/>
                                        <xs:element name="description">
                                            <xs:complexType>
                                                <xs:sequence maxOccurs="unbounded">
                                                    <xs:element name="p" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="example" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="input" type="xs:string"/>
                                                    <xs:element name="output" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="name" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                        <xs:attribute name="title" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="namespace" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== dd482IT/columnal-wpi/records/app/src/main/funcdoc/lookup.xml
<?xml version="1.0"?>
<functionDocumentation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                       xsi:noNamespaceSchemaLocation="funcdoc.xsd"
                       namespace="lookup">
    <functionGroup id="lookup" title="Lookup functions">
        <description>Functions for looking up one item in a list using another</description>
        <function name="lookup">
            <argType>([a], a, [b])</argType>
            <returnType>b</returnType>
            <description>
                <p>Given a list, finds a matching item, and returns the corresponding value from the other list.</p>
                <p>This is useful for looking up one column via the value of another, e.g. lookup(Column A, value in A, Column B)</p>
                <p>Gives an error if there are zero or multiple matches in the left side.</p>
            </description>
            <exampleGroup>
                <table name="Scores">
                    <column name="Person" type="Text">
                        Janet
                        Asim
                        Qing
                    </column>
                    <column name="Score" type="Number">
                        78
                        36
                        45
                    </column>
                </table>
                <example>
                    <inputDisplay>lookup(Person, "Qing", Score)</inputDisplay>
                    <inputParse>@call @function lookup(@entirecolumn Scores\Person, "Qing", @entirecolumn Scores\Score)</inputParse>
                    <output>45</output>
                </example>
                <example>
                    <inputDisplay>lookup(Person, "Hannah", Score)</inputDisplay>
                    <inputParse>@call @function lookup(@entirecolumn Scores\Person, "Hannah", @entirecolumn Scores\Score)</inputParse>
                    <output>error</output>
                </example>
            </exampleGroup>
            <example>
                <input>([4, 5, 6], 6, ["a", "b", "c"])</input>
                <output>"c"</output>
            </example>
            <example>
                <input>([1, 1, 2, 3], 6, ["a", "b", "c", "d"])</input>
                <output>error</output>
            </example>
        </function>        
        <function name="lookup single">
            <argType>([(a, b)], a)</argType>
            <returnType>b</returnType>
            <description>
                <p>Given a list of pairs, finds the single item with a matching left-hand value, and returns the right.</p>
                <p>This is useful for looking up one column via the value of another, e.g. lookup single(pair lists(Column A, Column B), value)</p>
                <p>Gives an error if there are zero or multiple matches in the left side.</p>
            </description>
            <example>
                <input>([(1, "a"), (2, "b")], 1)</input>
                <output>"a"</output>
            </example>
            <example>
                <input>([(1, "a"), (2, "b"), (1, "f")], 1)</input>
                <output>error</output>
            </example>
        </function>
        <function name="lookup all">
            <argType>([(a, b)], a)</argType>
            <returnType>[b]</returnType>
            <description>
                <p>Given a list of pairs, finds all the items with a matching left-hand value, and returns the right-hand values for each.</p>
                <p>This is useful for looking up one column via the value of another, e.g. lookup single(pair lists(Column A, Column B), value)</p>
            </description>
            <example>
                <input>([(1, "a"), (2, "b"), (1, "f")], 1)</input>
                <output>["a", "f"]</output>
            </example>
        </function>
    </functionGroup>
</functionDocumentation>

=== dd482IT/columnal-wpi/records/app/src/main/funcdoc/list.xml
<?xml version="1.0"?>
<functionDocumentation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                       xsi:noNamespaceSchemaLocation="funcdoc.xsd"
                       namespace="list">
    <function name="list length">
        <scope>t</scope>
        <argType>[t]</argType>
        <returnType>Number</returnType>
        <description>
            <p>Gets the number of elements in the given list.</p>
        </description>
        <example>
            <input>["a", "word", "list"]</input>
            <output>3</output>
        </example>
        <example>
            <input>[2, 4, 6, 8]</input>
            <output>4</output>
        </example>
        <example>
            <input>[]</input>
            <output>0</output>
        </example>
    </function>
    
    <function name="element">
        <scope>t</scope>
        <argType>([t], Number)</argType>
        <returnType>t</returnType>
        <description>
            <p>Gets the list element at the given position (first position is 1).</p>
        </description>
        <example>
            <input>(["x", "y", "z"], 1)</input>
            <output>"x"</output>
        </example>
        <example>
            <input>([2, 4, 6, 8], 4)</input>
            <output>8</output>
        </example>
        <example>
            <input>([], 1)</input>
            <output>error</output>
        </example>
        <example>
            <input>([true, false], 0)</input>
            <output>error</output>
        </example>
    </function>
</functionDocumentation>

=== dd482IT/columnal-wpi/records/app/src/main/funcdoc/core.xml
<?xml version="1.0"?>
<functionDocumentation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                       xsi:noNamespaceSchemaLocation="funcdoc.xsd"
                       namespace="core">
    <function name="asType">
        <argType>(Type t, t)</argType>
        <returnType>t</returnType>
        <description>
            <p>Clarifies the type of a value.</p>
            <p>No processing is done on the value; this function is only for specifying a type when it is ambiguous.  For conversions, see functions like from string.</p>
        </description>
        <example>
            <inputDisplay>(`Boolean`, from text("True"))</inputDisplay>
            <inputParse>(`Boolean`, @call @function from text("True"))</inputParse>
            <output>true</output>
        </example>
        <example>
            <input>(`[Date]`, [])</input>
            <output>[]</output>
        </example>
    </function>
    <function name="typeOf">
        <argType>t</argType>
        <returnType>Type t</returnType>
        <description>
            <p>Gets the type of the given value.</p>
        </description>
        <example>
            <input>asType(typeOf([3]), from text("[1, 2, 5]")</input>
            <output>[1, 2, 5]</output>
        </example>
    </function>
</functionDocumentation>

=== dd482IT/columnal-wpi/records/app/src/main/funcdoc/text.xml
<?xml version="1.0"?>
<functionDocumentation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                       xsi:noNamespaceSchemaLocation="funcdoc.xsd"
                       namespace="text">
    <function name="text length">
        <argType>Text</argType>
        <returnType>Number</returnType>
        <description>
            <p>Gets the length of the given text.</p>
            <p>Technical note: this is actually the number of Unicode codepoints in the text.  For English text without accents, one character is one codepoint.  If you have accents or non-English characters in your text, what looks like one character may be made up of multiple codepoints.</p>
        </description>
        <example>
            <input>"hello"</input>
            <output>5</output>
        </example>
        <example>
            <input>"a b."</input>
            <output>4</output>
        </example>
        <example>
            <input>""</input>
            <output>0</output>
        </example>
    </function>
    <function name="replace all">
        <argType>(Text, Text, Text)</argType>
        <returnType>Text</returnType>
        <description>
            <p>Replaces all occurrences of the first text with the second text, within the third text</p>
            <p>If the first text is empty, no replacement is performed.  If any occurrences overlap, the earlier part is replaced first.</p>
        </description>
        <example>
            <input>("at", "og", "The cat in the hat")</input>
            <output>"The cog in the hog"</output>
        </example>
        <example>
            <input>("oo", "a", "Mooo!")</input>
            <output>"Mao!"</output>
        </example>
        <example>
            <input>("", "x", "Orange")</input>
            <output>"Orange"</output>
        </example>
    </function>
</functionDocumentation>

=== dd482IT/columnal-wpi/records/app/src/main/funcdoc/conversion.xml
<?xml version="1.0"?>
<functionDocumentation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                       xsi:noNamespaceSchemaLocation="funcdoc.xsd"
                       namespace="conversion">
    <function name="from text">
        <scope>Readable t</scope>
        <argType>Text</argType>
        <returnType>t</returnType>
        <description>
            <p>Converts a value from text.</p>
            <p>This function works for any readable type (the only non-readable types are function types).  If the intended type cannot be inferred automatically, you may need to wrap this using the asType function.</p>
            <p>Some notes for specific types:</p>
            <ul>
                <li>For boolean values, lower-case and upper-case are allowed in the names.</li>
                <li>Dates are read using a variety of formats.  Be careful with the DD-MM-YY formats and similar as they are ambiguous against MM-DD-YY.  If this is an issue, use the date from string function to specify a format.</li>
                <li>Numbers must use dot as the decimal separator, commas are not supported.</li>
                <li>If you want to get a Text out of from text, it must be in quotes.</li>
            </ul>
        </description>
        <example>
            <input>from string("65") > 64</input>
            <output>true</output>
        </example>
        <example>
            <input>from string("TRUE") | false</input>
            <output>true</output>
        </example>
        <example>
            <input>asType(`Date`, from string("21st March 2004"))</input>
            <output>date(2004{year}, 3{month}, 21{day})</output>
        </example>
        <example>
            <input>asType(`[(Boolean, Number{m})]`, "[(true, 0{m}), (FALSE, -1.6{m}]")</input>
            <output>[(True, 0{m}), (False, -1.6{m})]</output>
        </example>
    </function>
</functionDocumentation>

=== dd482IT/columnal-wpi/records/app/src/main/funcdoc/boolean.xml
<?xml version="1.0"?>
<functionDocumentation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                       xsi:noNamespaceSchemaLocation="funcdoc.xsd"
                       namespace="boolean">
    <function name="not">
        <argType>Boolean</argType>
        <returnType>Boolean</returnType>
        <description>
            <p>Returns the opposite Boolean (given true, returns false; given false, returns true)</p>
        </description>
        <example>
            <input>true</input>
            <output>false</output>
        </example>
        <example>
            <input>false</input>
            <output>true</output>
        </example>
    </function>
</functionDocumentation>
