=== dd482IT/columnal-wpi/records/app/src/main/help/help.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="dialog">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="help" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="short" type="xs:string"/>
                            <xs:element name="full">
                                <xs:complexType>
                                    <xs:sequence maxOccurs="unbounded">
                                        <xs:element name="p" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                        <xs:attribute name="title" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
            <xs:attribute name="title" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== dd482IT/columnal-wpi/records/app/src/main/help/edit-unit.xml
<?xml version="1.0" encoding="UTF-8" ?>
<dialog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="help.xsd"
        id="edit-unit" title="Edit Unit Specification" >
    <help id="name" title="Unit Name">
        <short>The name of the unit of measurement.</short>
        <full>
            <p>Every unit must have name, and it cannot be the same name as other units (including built-in units like m for metre).</p>
            <p>Unit names must start with a letter or currency symbol (e.g. $) and can only contain letters, underscores and currency symbols.  They cannot contain numbers or spaces.</p>
        </full>
    </help>
    <help id="full" title="New Unit">
        <short>This creates a new unit (rather than just a new name for an existing unit).</short>
        <full>
            <p>Units can be defined as a multiple of another unit (e.g. a millimetre is 1/1000 of a metre) or totally independent of existing units.</p>
        </full>
    </help>
    <help id="description" title="Description">
        <short>Your description of the new unit, for your own reference.</short>
        <full>
            <p>Describe what the unit is, so you can remember later on what it is for.</p>
        </full>
    </help>
    <help id="definition" title="Definition">
        <short>You can define a unit as a multiple of an existing unit or combination of existing units.</short>
        <full>
            <p>A simple example is that you might want to define cL (short for centilitre) as 1/100th of a litre.  Often useful is to define a new name for a combination of units, for example you might want acc (short for acceleration) as a short name for m/s^2.</p>
            <p>You should only use this to define relationships which are fixed (e.g. 1cm = 0.01m).  For example, you could define a Euro to be 1.1 US dollars, but the exchange rate changes so it is not a good idea to fix it in the unit definition.</p>
        </full>
    </help>
    <help id="alias" title="Alias">
        <short>Makes a new name for an existing unit.</short>
        <full>
            <p>This makes a new name for an existing unit, for example you might want $ as a short name for USD.</p>
            <p>The key difference between using an alias and creating a new unit is that if you want to swap between two separate units, you must use a conversion function, whereas with an alias you do not.  So if you have two units 
                that are just different names for the same unit (for example, a shorter abbreviation for inch), use an alias.  If you have two different units that happen to be equivalent (for example, you might want a unit bagOfSugar which equals
                1 kilogram, but they are not measuring the same thing), define a full unit instead.</p>
        </full>
    </help>
    <help id="alias-target" title="">
        <short>The target for the alias.</short>
        <full>
            <p>For example, if you want to define f as a shorter name for foot, put "f" in the name field above, and put "foot" as the target in this field.</p>
        </full>
    </help>
</dialog>

=== dd482IT/columnal-wpi/records/app/src/main/help/edit-column.xml
<?xml version="1.0" encoding="UTF-8" ?>
<dialog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="help.xsd"
        id="edit-column" title="Edit Column Details" >
    <help id="column-name" title="Column Name">
        <short>The name used to refer to the column.</short>
        <full>
            <p>Every column must have a name, and you cannot have duplicate column names within a single table.</p>
            <p>Column names must start with a letter, optionally followed by a succession
            of numbers, letters and spaces.  You cannot have adjacent spaces, nor spaces at the beginning or end.</p>
        </full>
    </help>
    <help id="column-type" title="Column Type">
        <short>The type (e.g. number, text, date) of the values in the column.</short>
        <full>
            <p>All the values in a column must have the same type, such as number, text or date.</p>
            <p>Having all the values be of the same type avoids many errors in transformations, such as trying to multiple two text items together.</p>
            <p>If you need a column to have multiple types, use a tagged type.</p>
        </full>
    </help>
    <help id="column-defaultValue" title="Default Value">
        <short>The default value in the column when a new row is added.</short>
        <full>
            <p>Values in columns cannot be absent, so a default value is required for when a new row is added.</p>
            <p>If you want to have a "blank" value for a column, use a tagged type with a Blank tag.</p>
        </full>
    </help>
    <help id="column-expression" title="Column Expression">
        <short>This specifies the calculation of the column.</short>
        <full>
            <p>This is like a formula in a spreadsheet or mathematics.</p>
        </full>
    </help>
    <help id="table-name" title="Table Name">
        <short>The name of the table being created.</short>
        <full>
            <p>Every table must have a name, and tables may not share the same name.</p>
            <p>Table names must start with a letter, optionally followed by a succession
                of numbers, letters and spaces.  You cannot have adjacent spaces, nor spaces at the beginning or end.</p>
        </full>
    </help>
</dialog>

=== dd482IT/columnal-wpi/records/app/src/main/help/split-by.xml
<?xml version="1.0" encoding="UTF-8" ?>
<dialog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="help.xsd"
        id="split-by" title="Aggregate Split By" >
    <help id="whole-table" title="Whole Table">
        <short>Calculates the Aggregate expression(s) once for the whole table.</short>
        <full>
            <p>This will produce one output row for the Aggregate transformation, which calculates each expression once, using the whole table.  For example, group count will be the length of the table.</p>
        </full>
    </help>
    <help id="check-expression" title="Check Expression">
        <short>Calculates the Aggregate expression(s) multiple times, once for each unique combination of the chosen columns.</short>
        <full>
            <p>This will produce multiple output rows for the Aggregate transformation -- one for each unique combination of values in the chosen columns.  So if you have a column Animal with values like "Cat" and "Dog", and you split by Cat, you will calculate your expressions once for all Cat rows, and once for all Dog rows (and so on).  If you also split by a Size column (with values like "Small", "Large"), you'll get one output for Small Cat rows, one for Large Cat rows, one for Small Dog and so on.</p>
        </full>
    </help>
</dialog>

=== dd482IT/columnal-wpi/records/app/src/main/help/edit-r.xml
<?xml version="1.0" encoding="UTF-8" ?>
<dialog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="help.xsd"
        id="edit-r" title="Edit R Transformation">
    <help id="srctables" title="Tables to pass to R">
        <short>The tables to make available to the R expression.</short>
        <full>
            <p>Only the tables listed here are available to the R expression.  Table names are automatically adjusted to be valid R names if needed, and are listed below.</p>
        </full>
    </help>
    <help id="packages" title="Packages to load in R">
        <short>The packages to import for use in the R expression.</short>
        <full>
            <p>These packages will be imported (and installed, if needed) for you.  List them here, separated by commas.</p>
        </full>
    </help>
    <help id="expression" title="The R expression to run">
        <short>The R code to run and turn into a table.</short>
        <full>
            <p>The R code can have multiple lines.  The last line will be turned into a Columnal table.</p>
            <p>If it's a data frame it will be turned into a full table.  If it's a column or single value, it will be turned into a table with a single column.</p>
            <p>R types will be converted to the most suitable Columnal types.  Note that numbers in Columnal may be more precise than in R.</p>
        </full>
    </help>
</dialog>
